config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  
  root 'welcome#index'
  
  resources :notes
  resources :json_note

end

app/models/note.rb
class Note < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/json_note_controller.rb
class JsonNoteController < ApplicationController
    
    def index
        @notes = Note.all.order("created_at DESC")
        render json: @notes.to_json
    end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
    before_action :find_note, only: [:show, :edit, :update, :destroy]
    
    def index
        @notes = Note.all.order("created_at DESC")
    end
    
    def show
    end
    
    def new
        @note = Note.new
    end
    
    def create
        @note = Note.new(note_params)
        
        if @note.save
            redirect_to @note 
        else
            render 'new'
        end
        
    end
    
    def edit
    end
    
    def update
        if @note.update(note_params)
            redirect_to @note
        else
            render 'edit'
        end
    end
    
    def destroy
        @note.destroy
        redirect_to notes_path
    end
    
    private
    
        def find_note
            @note = Note.find(params[:id])
        end
        
        def note_params
            params.require(:note).permit(:title, :content)
        end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/json_note_helper.rb
module JsonNoteHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/notes/_form.html.haml
= simple_form_for @note do |f|
    = f.input :title
    = f.input :content
    = f.button :submit
    

app/views/notes/edit.html.haml
%h1 Fix Note !

= render 'form'

= link_to "Cancel", note_path

app/views/notes/index.html.haml
- @notes.each do |note|
    %h2= link_to note.title, note
    %p= time_ago_in_words(note.created_at)
    %p= truncate(note.content, length:50)
    
= link_to "Create Note", new_note_path

app/views/notes/new.html.haml
%h1 New Note !

= render 'form'

app/views/notes/show.html.haml
%h1= @note.title
%p= @note.content

=link_to "All Notes", notes_path
=link_to "Fix Note", edit_note_path(@note)
=link_to "Trash It", note_path(@note), method: :delete,  data: { confirm: "Are you sure?"  }

app/views/welcome/index.html.haml
%h1 Sistemin dogru calıstıgını gormek icin statik sayfa !!!
%p Sup my dudes, Bu sayfayı Home page olarak kullanmaya karar verdim şimdilik
%a{:href=>"/notes"} Tüm notlar
%p
%a{:href=>"/notes/new"} Yeni not
%p Özel bir not için x yerine idsini yazın mesela https://salty-gorge-50592.herokuapp.com/notes/3